name: A workflow to automate graph updates

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:
    inputs:
      runMessage:
        description: 'Run Message'
        required: true
        default: 'Testing'

jobs:
  build:
    name: Downloads Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Python script
        env:
          ACCOUNT_INFO: ${{ secrets.CLIENT_SECRETS }}
        run: |
          python download_update.py
      - name: Push changes to GitHub
        run: |
          git config --local user.email "bzlbzlbzl2000iscool@gmail.com"
          git config --local user.name "Bzlbzlbzl"
          git add download_data.json
          git commit -m "Updated downloads graph for last month"
          git push origin master
