name: A workflow to automate graph updates
on:
  schedule:
    - cron: '0 1 1 * *'
  push:
    branches:
      - master

jobs:
  build:
    name: Downloads Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "this is a test message!"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute download_update.py script
        env:
          ACCOUNT_INFO: ${{ secrets.CLIENT_SECRETS }}
        run: |
          python download_update.py
      - name: Commit changes to GitHub
        run: |
          git add download_data.json
          git commit -m "Updated downloads graph for last month"
          git push origin master
